### ISSUE TITLE
Connection issue with Growatt SPF5000ES

### ISSUE THREAD

**Issue by 3clypse** [sdsolomo/growatt-x000ES#3]
Hey! First of all, thanks for this repository, is quite helpful :)

After installing all dependencies, I plugged the USB A <-> USB B wire from the Raspberry PI to the Growatt inverter.
The `lsusb` command seems to show the USB connection, but I didn't see it on any `/dev/ttyUSB*`, so I suspect that the connection is not successful.

So after running the any *.py files this error is prompt:
```
[...]
raise ConnectionException("Failed to connect[%s]" % (self.str()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[rtu baud[9600]]
```

I guess the error is "normal" given the USB connection is not OK (?)
I also tried to use a RS232 RJ45 <-> USB A wire from the inverter to the RaspberryPI. This time `/dev/ttyUSB0` seems to be the interface available for this communication, but I still get the same Modbus error.

- I tried with other USB A <-> USB B cable. Maybe my inverter communication board is broken or different somehow?
- Any suggestion is welcome. I'm totally lost.

Thank you.

**Comment by 3clypse** [comment]
Update: Closing this issue as informative, given the communication boards are broken. I replaced them today (Growatt support sent me 2 new BMS + USB boards) and all work as expected.

Thank you.

**Comment by sdsolomo** [comment]
Hi, thanks!

The first thing I would try is a different usb cable.  Honestly, that
solves almost all of the issues that have been reported to me.

If that doesn't work, you might try again with a freshly burned flash card
for the pi.  I have seen a few goofy driver issues with randomly installed
apps.

Another troubleshooting step is to power on the growwatt with nothing
connected to the usb port.

Lastly, if you have access to a windows computer, you might try their
configuration tool to see if it can connect to the growwatt.

If none of that works for you, lmk and I will go further.

Thanks,
S
